# Render部署配置文件
# 用于部署到Render平台

services:
  - type: web
    name: enterprise-management-system
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm run preview -- --host 0.0.0.0 --port $PORT
    envVars:
      - key: VITE_SUPABASE_URL
        value: https://bikdpdwqsfrflvplzrxy.supabase.co
      - key: VITE_SUPABASE_ANON_KEY
        value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJpa2RwZHdxc2ZyZmx2cGx6cnh5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc1MjY3MjYsImV4cCI6MjA3MzEwMjcyNn0.O7zgDEiDiHykHf7EcRUGDTDSZ2tKJdTJie07P0kwm2Y
